services:
  db:
    image: postgres:15.0
    container_name: cp-db-dev
    environment:
      POSTGRES_DB: careerpath_dev
      POSTGRES_USER: cp_user
      POSTGRES_PASSWORD: cp_pass
    ports:
      - "5432:5432"
    volumes:
      - cp_pg_data:/var/lib/postgresql/data
    networks:
      - cp-net
    restart: unless-stopped

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile-dev
    container_name: cp-backend-dev
    command: gradle bootRun
    volumes:
      - ../../backend:/app
    ports:
      - "8080:8080"
    env_file:
      - ../env/.env.dev
    depends_on:
      - db
    networks:
      - cp-net
    restart: unless-stopped

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile-dev
    container_name: cp-frontend-dev
    command: npm run start
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - cp-net
    restart: unless-stopped
