services:
  db-local:
    image: postgres:15
    container_name: cp-db-local
    environment:
      POSTGRES_DB: careerpath_local
      POSTGRES_USER: cp_user
      POSTGRES_PASSWORD: cp_pass
    ports:
      - "55432:5432"
    networks:
      - cp-net

networks:
  cp-net:
    driver: bridge