version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: careerpath_test
      POSTGRES_USER: cp_user
      POSTGRES_PASSWORD: cp_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cp_user -d careerpath_test" ]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    image: cp-backend-ci
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["./gradlew"]
    command: ["integrationTest", "--no-daemon", "-Dtestcontainers.cloud.enabled=true"]
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/careerpath_test
      SPRING_DATASOURCE_USERNAME: cp_user
      SPRING_DATASOURCE_PASSWORD: cp_pass
      TESTCONTAINERS_LOG_LEVEL: DEBUG

      TESTCONTAINERS_CLOUD_TOKEN: ${TC_CLOUD_TOKEN}
