version: "3.9"

services:
  db:
    image: postgres:15
    container_name: cp-db-dev
    environment:
      POSTGRES_DB: careerpath_dev
      POSTGRES_USER: cp_user
      POSTGRES_PASSWORD: cp_pass
    ports:
      - "5432:5432"
    volumes:
      - cp_pg_data_dev:/var/lib/postgresql/data
    networks:
      - cp-net

  backend:
    user: root
    build:
      context: ../../backend
      dockerfile: Dockerfile.dev
      args:
        DOCKER_GID: 1001
    container_name: cp-backend-dev
    command: ./gradlew bootRun
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://cp-db-dev:5432/careerpath_dev
      SPRING_DATASOURCE_USERNAME: cp_user
      SPRING_DATASOURCE_PASSWORD: cp_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
      TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gradle_cache:/home/gradle/.gradle
    depends_on:
      - db
    networks:
      - cp-net

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.dev
    container_name: cp-frontend-dev
    command: npm run start
    environment:
      - CHOKIDAR_USEPOLLING=true
      - API_URL=http://cp-backend-dev:8080/api
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - cp-net

networks:
  cp-net:
    driver: bridge

volumes:
  cp_pg_data_dev:
  gradle_cache:
